### ISSUE TITLE
Already exist repository need to update

### ISSUE THREAD

**Issue by Noriko-Nakamura** [MojithaR/Git-Insight#15]
Once I update a repository should I need to use this command 
"# Add a remote repository URL git remote add origin http://your.git.repo.url/repository.git"
again, when I need to update the same repository again?

**Comment by MojithaR** [comment]
Not really, just use these commands.
git status --to check your updated code files
git add . --Add all files
git commit -m "Initial commit" -- Commit the files with a message
git push -u origin master --Push changes to the remote repository

important the project need to update in the same repository.
